# Generated by Django 4.2.3 on 2023-08-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polygone', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polygone',
            name='name',
        ),
    ]
