# Generated by Django 4.2.3 on 2023-08-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_customuser_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='isSupervisor',
            field=models.BooleanField(default=False),
        ),
    ]
